[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_ido_platform = "9ghHF9QjUqzR9RLMasz6niBTQyCD6TMpc85yy1g2ioo6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hulk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
